export interface IApiDatum {
  airmass: number | null;
  archive_url: string | null;
  cutout_url: string | null;
  date: string;
  ddec: number;
  dec: number;
  delta: number;
  designation?: string;
  dra: number;
  drh: number;
  elong: number;
  exposure: number;
  filter: string | null;
  instrument?: string | null;
  jd?: number;
  maglimit: string | null;
  mjd_start: number;
  mjd_stop: number;
  phase: number;
  preview_url: string | null;
  product_id: string;
  ra: number;
  // raDec?: string;
  rdot?: number;
  rh: number;
  sangle: number;
  seeing: number | null;
  selong?: number;
  source: string;
  source_name: string;
  thumbnail_url?: string | null;
  tmtp?: number;
  true_anomaly: number;
  unc_a: number;
  unc_b: number;
  unc_theta: number;
  vangle: number;
  vmag: number;
}
