#! /bin/bash

# Confirm
clear
echo """

======================================================================
Are you certain you want to destroy all your terraform infrastructure?

Type 'yes' to confirm.

======================================================================

"""
read decision

if [[ $decision != 'yes' ]]; then
  echo "Cancelling..."
  exit
fi

# First empty buckets
source .env
aws s3 rm s3://${TF_VAR_DEV_BUCKET_NAME} --recursive
aws s3 rm s3://${TF_VAR_PROD_BUCKET_NAME} --recursive

# For some reason, need to specify region in env var or get weird error
# From: https://github.com/terraform-providers/terraform-provider-aws/issues/9989#issuecomment-558389160
AWS_DEFAULT_REGION='us-east-1' terraform destroy
