#! /bin/bash

clear

echo -e """
\033[32m
===============================
RUNNING WEBPACK-BUNDLE-ANALYZER
===============================
\033[0m
"""

./node_modules/.bin/webpack-bundle-analyzer ./dist/catch-gui-prod/stats*.json
