/**
 *
 */
export const panstarrsRequestedColumns = [
  'objID',
  // 'projectionID',
  // 'skyCellID',
  // 'objInfoFlag',
  'qualityFlag',
  'raMean',
  'decMean',
  'raMeanErr',
  'decMeanErr',
  // 'epochMean',
  // 'nStackDetections',
  'nDetections',
  // 'ng',
  // 'nr',
  // 'ni',
  // 'nz',
  // 'ny',
  // 'gQfPerfect',
  // 'gMeanPSFMag',
  // 'gMeanPSFMagErr',
  // 'gMeanPSFMagStd',
  // 'gMeanPSFMagNpt',
  // 'gMeanPSFMagMin',
  // 'gMeanPSFMagMax',
  // 'gMeanKronMag',
  // 'gMeanKronMagErr',
  // 'gFlags',
  // 'rQfPerfect',
  // 'rMeanPSFMag',
  // 'rMeanPSFMagErr',
  // 'rMeanPSFMagStd',
  // 'rMeanPSFMagNpt',
  // 'rMeanPSFMagMin',
  // 'rMeanPSFMagMax',
  // 'rMeanKronMag',
  // 'rMeanKronMagErr',
  // 'rFlags',
  // 'iQfPerfect',
  // 'iMeanPSFMag',
  // 'iMeanPSFMagErr',
  // 'iMeanPSFMagStd',
  // 'iMeanPSFMagNpt',
  // 'iMeanPSFMagMin',
  // 'iMeanPSFMagMax',
  // 'iMeanKronMag',
  // 'iMeanKronMagErr',
  // 'iFlags',
  // 'zQfPerfect',
  // 'zMeanPSFMag',
  // 'zMeanPSFMagErr',
  // 'zMeanPSFMagStd',
  // 'zMeanPSFMagNpt',
  // 'zMeanPSFMagMin',
  // 'zMeanPSFMagMax',
  // 'zMeanKronMag',
  // 'zMeanKronMagErr',
  // 'zFlags',
  // 'yQfPerfect',
  // 'yMeanPSFMag',
  // 'yMeanPSFMagErr',
  // 'yMeanPSFMagStd',
  // 'yMeanPSFMagNpt',
  // 'yMeanPSFMagMin',
  // 'yMeanPSFMagMax',
  // 'yMeanKronMag',
  // 'yMeanKronMagErr',
  // 'yFlags',
] as const;
